server:
  port: 8181
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript

eureka:
  instance:
    hostname: ${reportportal.eureka.instance.hostname:localhost}
  client:
    serviceUrl:
      defaultZone: http://${reportportal.eureka.hostname:localhost}:8761/eureka/